### ISSUE TITLE
Broken since the big update that broke most mods

### ISSUE THREAD

**Issue by maboutin81** [Deahgib/AnglerAtlas#3]
Since the big update that broke most mods:

Message: Interface/AddOns/AnglerAtlas/UI.lua:19: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
Time: Sun Oct 20 13:22:57 2024
Count: 1
Stack: Interface/AddOns/AnglerAtlas/UI.lua:19: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@Interface/AddOns/AnglerAtlas/UI.lua"]:19: in function `BuildAddonSettings'
[string "@Interface/AddOns/AnglerAtlas/UI.lua"]:1446: in function `Build'
[string "@Interface/AddOns/AnglerAtlas/Core.lua"]:28: in function <Interface/AddOns/AnglerAtlas/Core.lua:26>
[string "@Interface/AddOns/AnglerAtlas/Core.lua"]:45: in function <Interface/AddOns/AnglerAtlas/Core.lua:43>

Locals: self = angler-root {
 ANGLER_DARK_FONT_COLOR = ""
 TopLeftCorner = Texture {
 }
 selectedZoneHighlight = angler-zone-selected-icon {
 }
 TopBorder = Texture {
 }
 selectedIcon = angler-grid-selected-icon {
 }
 equipmentToggleButton = angler-tab-button-1 {
 }
 TitleBg = Texture {
 }
 showButtonTab = angler-show-button-tab {
 }
 recipesToggleButton = angler-tab-button-1 {
 }
 TitleText = FontString {
 }
 BotRightCorner = Texture {
 }
 title = FontString {
 }
 zoneinfo = angler-zone-info {
 }
 tabManager = <table> {
 }
 fishIcons = <table> {
 }
 characterPortrait = angler-character-portrait {
 }
 RightBorder = Texture {
 }
 LeftBorder = Texture {
 }
 recipes = angler-recipes-info {
 }
 topBanner = Texture {
 }
 ANGLER_BACKDROP = <table> {
 }
 info = angler-fish-info {
 }
 TopRightCorner = Texture {
 }
 grid = angler-grid {
 }
 Bg = Texture {
 }
 zones = angler-fish-info {
 }
 playerInfo = FontString {
 }
 TopTileStreaks = Texture {
 }
 playerName = FontString {
 }
 BottomBorder = Texture {
 }
 equipment = angler-equipment-info {
 }
 CloseButton = Button {
 }
 BotLeftCorner = Texture {
 }
}
panel = Frame {
 name = "AnglerAtlas"
}
(*temporary) = nil
(*temporary) = Frame {
 name = "AnglerAtlas"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
LibDBIcon = <table> {
 callbacks = <table> {
 }
 radius = 5
 tooltip = LibDBIconTooltip {
 }
 objects = <table> {
 }
 callbackRegistered = true
}

**Comment by Deahgib** [comment]
Thank you for flagging this I will be publishing a fix as soon as I am able.

**Comment by Deahgib** [comment]
Hi @maboutin81 thanks for the interest in the addon's update. I believe I have a fix, however I currently don't have a sub to test it, could you manually install a test fix version of the addon I made here, https://github.com/Deahgib/AnglerAtlas/blob/patch-11.0.2-settings-API-changes/dist/AnglerAtlas-0.0.10testfix.zip
And report back if there are any bugs? Note the changes are related to the creation of the settings page of the addon.  If the problem is fixed I can publish the changes to curseforge.

**Comment by maboutin81** [comment]
Will do it now. Sorry for late response.

**Comment by maboutin81** [comment]
Looks like it's working perfectly. =D

**Comment by Deahgib** [comment]
Thanks very much @maboutin81 the fix is on curseforge now too
